version: '3.7'

volumes:
  fuseki_data:

networks:
  skosmos:
    driver: bridge
    ipam:
      config:
      - subnet: 172.20.0.0/16

services:

  jena:
    image: stain/jena:3.10.0

  fuseki:
    build: fuseki
    restart: always
    environment:
     - JVM_ARGS=-Xmx4g
     - ADMIN_PASSWORD
    volumes:
     - fuseki_data:/fuseki
    ports:
     - "3031:3030"
    networks:
     - skosmos

  fuseki_cache:
    build: fuseki_cache
    restart: always
    depends_on:
     - fuseki
    environment:
     - VCL_CONFIG=/varnish.vcl
     - CACHE_SIZE=256m
    ports:
     - "3030:80"
    networks:
     - skosmos

  skosmos:
    build: skosmos
    restart: always
    environment:
      - CURRENT_BRANCH
      - GITHUB_TOKEN
    ports:
     - "8000:80"
    depends_on:
     - fuseki_cache
    networks:
     - skosmos

  skosmos_cache:
    build: skosmos_cache
    restart: always
    depends_on:
     - skosmos
    environment:
     - VCL_CONFIG=/varnish.vcl
     - CACHE_SIZE=256m
    ports:
     - "8001:80"
    networks:
     - skosmos

