
# Data-only container
fuseki_data:
  build: fuseki_data

# Jena command line tools
jena:
  image: stain/jena

# Fuseki service
fuseki:
  build: fuseki
  restart: on-failure:3
  ports:
   - "3030:3030"
  volumes_from:
   - fuseki_data

# Skosmos service
skosmos:
  build: skosmos
  ports:
   - "8000:80"
  links:
  - fuseki
