version: '3'

volumes:

  # Fuseki data
  fuseki_data:

services:

  # Jena command line tools
  jena:
    image: stain/jena

  # Fuseki service
  fuseki:
    build: fuseki
    restart: always
    environment:
     - JVM_ARGS=-Xmx4g
    volumes:
     - fuseki_data:/fuseki
    ports:
     - "3031:3030"

  fuseki_cache:
    build: fuseki_cache
    restart: always
    links:
     - fuseki
    environment:
     - VCL_CONFIG=/varnish.vcl
     - CACHE_SIZE=256m
    ports:
     - "3030:80"

  # Skosmos service
  skosmos:
    build: skosmos
    restart: always
    ports:
     - "8000:80"
    links:
     - fuseki_cache

  skosmos_cache:
    build: skosmos_cache
    restart: always
    links:
     - skosmos
    environment:
     - VCL_CONFIG=/varnish.vcl
     - CACHE_SIZE=256m
    ports:
     - "8001:8000"
