
# Data-only container
fuseki_data:
  build: fuseki_data

# Jena command line tools
jena:
  image: stain/jena

# Fuseki service
fuseki:
  build: fuseki
  restart: always
  environment:
   - JVM_ARGS=-Xmx2g
  volumes_from:
   - fuseki_data
  ports:
   - "3031:3030"

fuseki_cache:
  build: fuseki_cache
  restart: always
  links:
   - fuseki
  environment:
   - VCL_CONFIG=/varnish.vcl
   - CACHE_SIZE=256m
  ports:
   - "3030:80"

# Skosmos service
skosmos:
  build: skosmos
  restart: always
  ports:
   - "8000:80"
  links:
   - fuseki_cache

